/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
* -------------------------------------------------------------
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5c6d27c3f2450f0d8665c26b
*
* You will get 10% discount for each one of your friends
* 
*/
/**

  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
                                                                                     
                                                                                   
 *  DO NOT EDIT HIS FILE!!
 * 
 *  FOR CUSTOMIZE DB SCHEMA PLEASE EDIT db/Manage_Film_Example_db_customSchema.js
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT EASYDEV'S CODE GENERATION --
 * 
 */

const mongoose = require('mongoose');
const Schema = mongoose.Schema;
const createUser = require('../security/security.js');

const db_Manage_Film_Example_db_schema = [];
const db_Manage_Film_Example_db = [];

/**
 * SCHEMA DB Manage_Film_Example_db
 */



 /**
  * Actor
  */
db_Manage_Film_Example_db_schema.Actor = new mongoose.Schema({
	birthDate: {
		type: 'Date'
	},
	name: {
		type: 'String', 
		required : true
	},
	surname: {
		type: 'String'
	},
	//RELATIONS
	
	
	//EXTERNAL RELATIONS
	/*
	cast: [{
		type: Schema.ObjectId,
		ref : "Film"
	}],
	*/
});


 /**
  * Film
  */
db_Manage_Film_Example_db_schema.Film = new mongoose.Schema({
	genre: {
		type: 'String',
		enum : ["Action","Crime","Fantasy","Horror"], 
	},
	title: {
		type: 'String', 
		required : true
	},
	year: {
		type: 'Number'
	},
	//RELATIONS
	cast: [{
		type: Schema.ObjectId,
		ref : "Actor"
	}],
	filmMaker: {
		type: Schema.ObjectId, 
		required : true,
		ref : "FilmMaker"
	},
	
	
	//EXTERNAL RELATIONS
	/*
	*/
});


 /**
  * FilmMaker
  */
db_Manage_Film_Example_db_schema.FilmMaker = new mongoose.Schema({
	name: {
		type: 'String', 
		required : true
	},
	surname: {
		type: 'String'
	},
	//RELATIONS
	
	
	//EXTERNAL RELATIONS
	/*
	filmMaker: {
		type: Schema.ObjectId, 
		required : true,
		ref : "Film"
	},
	*/
});


 /**
  * User
  */
db_Manage_Film_Example_db_schema.User = new mongoose.Schema({
	mail: {
		type: 'String'
	},
	name: {
		type: 'String'
	},
	password: {
		type: 'String', 
		required : true
	},
	roles: [{
		type: 'String'
	}],
	surname: {
		type: 'String'
	},
	username: {
		type: 'String', 
		required : true
	},
	//RELATIONS
	
	
	//EXTERNAL RELATIONS
	/*
	*/
});



// Import schema customization
require('./Manage_Film_Example_db_customSchema.js');
var Manage_Film_Example_db_model = require('./Manage_Film_Example_db_crud.js');

// Declare mongoose model

db_Manage_Film_Example_db.Actor = Manage_Film_Example_db_model.connection.model('Actor', db_Manage_Film_Example_db_schema.Actor );
db_Manage_Film_Example_db.Film = Manage_Film_Example_db_model.connection.model('Film', db_Manage_Film_Example_db_schema.Film );
db_Manage_Film_Example_db.FilmMaker = Manage_Film_Example_db_model.connection.model('FilmMaker', db_Manage_Film_Example_db_schema.FilmMaker );
db_Manage_Film_Example_db.User = Manage_Film_Example_db_model.connection.model('User', db_Manage_Film_Example_db_schema.User );

module.exports = db_Manage_Film_Example_db;

// Create ADMIN user if does not exist
createUser.createUser();
